### ISSUE TITLE
Services?

### ISSUE THREAD

**Issue by Crease29** [PAYONE-GmbH/shopware-5#116]
Hello,

I'm writing a plugin that imports retours from a logistics service as CLI command.
When a retour comes in the plugin has to refund the returned positions.
So I thought I'll have a look into the workflow that is used in the backend (see \Shopware_Controllers_Backend_MoptPayoneOrder::moptPayoneDebitAction()).

Because you use `$this->Request()` here, which is understandable, I copied your controller and had to refactor the init() method in this controller to inject the services.
This makes hell a lot problems because the needed classes aren't available in the DIC.

So my question is: Do you have *any* services in your plugin that let me refund orders?

**Comment by fjbender** [comment]
Hi @Crease29,

we already have some undocumented methods for this in Bootstrap.php. However, we're currently working on moving these methods into a service, so that they can be used independently from Bootstrap.php (which isn't a nice way to begin with, but we had our reasons).

Stay tuned for further updates.

**Comment by fjbender** [comment]
Fixed with #131
