### ISSUE TITLE
Plugin exposes CC Data by using GET-Parameter

### ISSUE THREAD

**Issue by chess-levin** [PAYONE-GmbH/shopware-5#204]
Tested on Shopware 5.3.7 und PayOne 3.8.2

```https://secure.pay1.de/client-api/?request=creditcardcheck&responsetype=JSON&mode=test&mid=40311&aid=40509&portalid=2029021&encoding=UTF-8&storecarddata=yes&hash=aee55c5dddd08dd915567b05074b96ee&cardpan=4111131010111111&cardexpiremonth=12&cardexpireyear=2018&cardtype=V&channelDetail=payoneHosted&cardcvc2=123&callback_method=PayoneGlobals.callback```

The creditcardcheck API call uses a GET-Request with URL-Paramters. This unnecessarily exposes cc data. It is recommend as secure coding best practice to submit sensitve data by using POST-Parameter (see Common Weakness Enumerations https://cwe.mitre.org/data/definitions/598.html) 
Using URL parameters could lead to a disclousure of cc data in webservers accesslogs.  

A POST request is already handled by the API. Best practice would be to allow the controller only requests using method type POST to be executed. Changing the implementation to POST is part of the defense in depth strategy of it-security, which here creates a fallback against the (weak) default configuration of webserver log settings.

Greetings
Sven Scheil
hmmh multimediahaus ag

**Comment by fjbender** [comment]
Thank you for your feedback. In general, I share your arguments. Credit card data should always be handled in the safest way possible.

The GET request payload itself is encrypted, as the encryption is taking place on the Transport Layer. The entire communication between the customer's web browser and our platform thus is secure to the extend of state of the art principles.

CWE-598 is, however, not completely applicable here. Since the credit card data is directly sent into our Card Data Environment, we ensure that it only is stored in a compliant way and not logged anywhere it shouldn't be. We are frequently audited by Qualified Security Assessors to maintain our PCI Compliance certification. Additionally, we conduct regular penetration tests, as required by PCI DSS, and other security measures.

I share your point that at first sight this creates a little bit of "cringe". However, in this case there is nothing to be worried about.

Best
Florian
