### ISSUE TITLE
Uncaught Error: Call to a member function getArrayCopy() on null

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#37]
just found this one:

[Tue Oct 04 18:01:37.121008 2016] [:error] [pid 4936] [client 10.6.219.2:48338] PHP Fatal error:  Uncaught Error: Call to a member function getArrayCopy() on null in /var/www/xxxxxxxxxx/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php:77\nStack trace:\n#0 /var/www/xxx.xxx.xxx/htdocs/engine/Library/Enlight/Controller/Action.php(159): Shopware_Controllers_Frontend_MoptShopNotification->indexAction()\n#1 /var/www/xxx.xxx.xxx/htdocs/engine/Library/Enlight/Controller/Dispatcher/Default.php(523): Enlight_Controller_Action->dispatch('indexAction')\n#2 /var/www/xxx.xxx.xxx/htdocs/engine/Library/Enlight/Controller/Front.php(223): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))\n#3 /var/www/xxx.xxx.xxx/htdocs/engine/Shopware/Kernel.php(176): Enlight_Controller_Front->dispatch()\n#4 /var/www/xxx.xxx.xxx/htdocs/vendor/symfony/http-kernel/HttpCache/HttpCach in /var/www/xxx.xxx.xxx/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php on line 77

**Comment by elbsurfer** [comment]
Hello,
I just had the same issue. Is there any news regarding this issue? Why it occurs and how we can prevent it?

**Comment by fjbender** [comment]
Unfortunately, we're not quite sure what causes this problem here.

**Comment by elbsurfer** [comment]
@fjbender I assume the session can not be restored for some reason. Can you tell me what the implications of this error are?  The user is getting a 500 error in the frontend, right? Is the order still stored in SW?

**Comment by fjbender** [comment]
In this particular case here, the error occurs when the Payone platform tries to deliver the asynchronous notification ("Transactionstatus"). This means that the payment status of the order probably wasn't updated correctly. In the instance #81, the error occurred in the frontend and the reporter there describes that the order is then lost.

However, we haven't been able to systematically reproduce this error. If you have any insights here, it is much appreciated.

**Comment by elbsurfer** [comment]
I did a debug statement as follows:

```
$this->restoreSession($request->getParam('param'));
$session = Shopware()->Session();
if (!isset($session['sOrderVariables'])) {
       error_log($request->getParam('param'));
       error_log(json_encode($session));
}
$orderVariables = $session['sOrderVariables']->getArrayCopy();
```

The result is:

```
mod_fcgid: stderr: session-1|0r983lpsrptmsgk872tqq5bvn7|c41a6d936bdaf00941e2f2e588740c49
mod_fcgid: stderr: {}
mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function getArrayCopy()
```

So restoreSession splits this string based on | and takes the result with key 1. So the question is, why is the session "0r983lpsrptmsgk872tqq5bvn7" not available. What reasons can this have? Does somebody needs to much time for the payment? 

We have tons of these errors in our logs since a few days.

**Comment by fjbender** [comment]
Thanks for the detailed info. The way we rely on the session being available is quite prone to errors, and that definitely not ideal. 

Does this affect all orders or only some? Are mostly redirect payment methods (like PayPal, Sofort, Credit Card with 3D Secure, ...) affected?

**Comment by elbsurfer** [comment]
I did a look through the logs again and I think I solved it on our end. 

The SwagAdvancedCart plugin was, somehow, throwing errors since 2 days. Why this is the case, I do not know, because nothing as changed on our end - no deployment, no change of the environment or whatever.

But the error was this one - referer checkout is always not a good sign:
`[fcgid:warn] mod_fcgid: stderr: PHP Fatal error:  Uncaught SmartyException: directory '/engine/Shopware/Plugins/Community/Frontend/SwagAdvancedCart/Views/frontend/index/index.tpl' not allowed by security setting in /engine/Library/Smarty/sysplugins/smarty_security.php:381, referer: https://domain.de/checkout`

This error is only thrown in the checkout - I do not know why, but because this error was thrown I think that the sOrderVariables are not correctly written in the session. So the PayOne plugins fails when coming back and the order remains as a temporary order in the database. I also do not know why this happens in some cases and not for all users who finish the checkout.

**Comment by fjbender** [comment]
Okay. Get back to me anytime if anything new arises.

**Comment by plivinskiy** [comment]
Hello,
the problem is in the sessionID you should use temporaryID from the table s_order to restore the order, because the sessionID can be deleted if user click on logout or session is expired.

**Comment by elbsurfer** [comment]
@fjbender Behebt die Version 3.9.0 des Plugins diesen Fehler?

**Comment by fjbender** [comment]
@elbsurfer Nicht wissentlich - wir haben an dieser Stelle nichts bearbeitet, da immer noch die Möglichkeit zur systematischen Reproduktion fehlt.

**Comment by fjbender** [comment]
@elbsurfer 

I still couldn't reproduce the issue here with 10 Minutes waiting time before completing the PayPal checkout.

However, I suppose that in a real life scenario with traffic on the shop the garbage collection kicks in and removes the session, so that we can't use it anymore to finalize the order. Maybe it's possible that you fiddle with the garbage collection settings to increase the time where the session can be restored?

**Comment by irwinbraganza** [comment]
@fjbender I am too facing this issue, occurs for me just after the succesful sofort payment and before the checkout finishAction (Thank you page) is called, here is the error:
`PHP Fatal error:  Uncaught Error: Call to a member function getArrayCopy() on null in /var/www/html/production/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php:79`

**Comment by hreinberger** [comment]
I'm guessing this can be safely closed?

**Comment by DavRet** [comment]
We are still facing this issue and got plenty of errors like this in our logs:

`PHP Fatal error:  Uncaught Error: Call to a member function getArrayCopy() on null `

Our system:

- Shopware v5.6.8
- PAYONE Payment Plugin 4.11.0


Unfortunately this also happened to us:

> We had the issue again that a user was forwarded to PayPal, paid via PayOne and the order was not in our system. 



Could you please investigate this issue?

**Comment by dmetoglou** [comment]
@DavRet Does this happen with all PayPal payments?
If yes, kindly contact our tech support to have a look at your transactions.

I assume that the error occurs when the Payone platform tries to deliver the asynchronous notification. This means that the payment status of the order probably wasn't updated correctly.
