### ISSUE TITLE
Shopware 5.7 

### ISSUE THREAD

**Issue by DirkPersky** [PAYONE-GmbH/shopware-5#424]
For Shopware 5.7

u need to lowercase the DIJ

from:
```php
        $this->get('Snippets')->addConfigDir($this->Path() . 'Snippets/');
```

too:
```php
        $this->get('snippets')->addConfigDir($this->Path() . 'Snippets/');
```

**Comment by hreinberger** [comment]
@jvarelmann could you have a look?

**Comment by jvarelmann** [comment]
Hello,

can you tell where the typo should be changed and what kind of error it produce ?

LG Juergen

**Comment by jvarelmann** [comment]
Hello, at the moment we don´t have an offical Relese for SW 5.7 , in the new release the the error with the function is fixed

regards Juergen

**Comment by OfflineVibe** [comment]
> can you tell where the typo should be changed and what kind of error it produce ?
You can find it over at
https://github.com/PAYONE-GmbH/shopware-5/blob/master/Frontend/MoptPaymentPayone/Bootstrap.php
Line 67

When trying to upgrade Shopware to 5.7.2 with Payone Installed, the Shop won't work at all, Frontend and Backend can't be reached/blank screens. I had to install a backup. The error I received by PHP looked like this:
`PHP Fatal error: Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException: You have requested a non-existent service "Snippets"`

> Hello, at the moment we don´t have an offical Relese for SW 5.7 , in the new release the error with the function is fixed
Is there going to be an update soon? We would love to update our shops to SW 5.7.2 since it has security fixes.

**Comment by jvarelmann** [comment]
Hello , we just released a beta version , where the  Symfony error is fixed

**Comment by hreinberger** [comment]
Hi all, we've just tagged Version 4.5.0 which has been tested with Shopware 5.7.2. We've also released this version in the Shopware Store!
